CREATE TABLE activities (
    id BIGINT PRIMARY KEY,
    name TEXT,
    distance NUMERIC(12, 6),
    moving_time INTEGER,
    elapsed_time INTEGER,
    total_elevation_gain NUMERIC(12, 6),
    sport_type TEXT,
    workout_type INTEGER,
    start_date TIMESTAMP,
    start_date_local TIMESTAMP,
    timezone TEXT,
    utc_offset REAL,
    location_city TEXT,
    location_state TEXT,
    location_country TEXT,
    achievement_count INTEGER,
    kudos_count INTEGER,
    comment_count INTEGER,
    athlete_count INTEGER,
    trainer BOOLEAN,
    commute BOOLEAN,
    manual BOOLEAN,
    private BOOLEAN,
    visibility TEXT,
    flagged BOOLEAN,
    gear_id TEXT,
    start_lat NUMERIC(9, 6),
    start_lng NUMERIC(9, 6),
    end_lat NUMERIC(9, 6),
    end_lng NUMERIC(9, 6),
    average_speed NUMERIC(10, 6),
    max_speed NUMERIC(10, 6),
    average_cadence NUMERIC(6, 2),
    average_temp NUMERIC(6, 2),
    average_watts NUMERIC(6, 2),
    max_watts INTEGER,
    weighted_average_watts INTEGER,
    kilojoules NUMERIC(10, 2),
    device_watts BOOLEAN,
    has_heartrate BOOLEAN,
    average_heartrate NUMERIC(6, 2),
    max_heartrate NUMERIC(6, 2),
    elev_high NUMERIC(10, 6),
    elev_low NUMERIC(10, 6),
    upload_id BIGINT,
    external_id TEXT,
    pr_count INTEGER,
    suffer_score NUMERIC(6, 2)
);